// <auto-generated />
using MBR.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace MBR.Migrations
{
    [DbContext(typeof(Context))]
    partial class EmployeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MBR.Models.BrokerCustomer", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MLS_Id");

                    b.Property<bool>("employerApproved");

                    b.Property<bool>("insuranceApproved");

                    b.Property<string>("name");

                    b.Property<int>("value");

                    b.HasKey("ID");

                    b.ToTable("brokerCustomers");
                });

            modelBuilder.Entity("MBR.Models.Employee", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("employeeId");

                    b.Property<string>("name");

                    b.Property<string>("position");

                    b.Property<long>("salary");

                    b.Property<long>("years");

                    b.HasKey("id");

                    b.ToTable("employerEmployees");
                });

            modelBuilder.Entity("MBR.Models.EmployeeCallbackURL", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("applicationId");

                    b.Property<string>("callBackId");

                    b.HasKey("id");

                    b.ToTable("employeeUrls");
                });

            modelBuilder.Entity("MBR.Models.InsuranceProperty", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MLS_Id");

                    b.Property<string>("clientName");

                    b.Property<double>("deductable");

                    b.Property<double>("insuredValue");

                    b.HasKey("id");

                    b.ToTable("insuranceProperties");
                });

            modelBuilder.Entity("MBR.Models.MunicipalProperty", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MLS_Id");

                    b.Property<string>("police");

                    b.Property<string>("schools");

                    b.Property<string>("sewage");

                    b.Property<string>("water");

                    b.HasKey("id");

                    b.ToTable("municipalProperties");
                });

            modelBuilder.Entity("MBR.Models.RealEstate", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MLS_Id");

                    b.Property<string>("MortId");

                    b.HasKey("id");

                    b.ToTable("realEstates");
                });

            modelBuilder.Entity("MBR.Models.RealEstateCallbackURL", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MLS_Id");

                    b.Property<string>("MortId");

                    b.Property<string>("urlString");

                    b.HasKey("id");

                    b.ToTable("realEstateCallbackURLs");
                });
#pragma warning restore 612, 618
        }
    }
}
